<!doctype html>

<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.9">

  <title>Enduro</title>

  <link rel="stylesheet" href="/assets/css/fontawesome/web-fonts-with-css/css/fontawesome-all.min.css"/> 
  <link rel="stylesheet" href="/assets/css/style4.css"/>
  <script src="/assets/js/jquery-3.3.1.min.js"></script>  
  <script src="/assets/js/script2.js"></script>

  <script type="text/javascript">
    var evento_id='<?= $evento_id ?>';
    var username='<?= $username ?>';
  </script>

</head>

<body>

    <p>Tela de administração de Enduro</p>
    <p><?= $evento_id ?></p>
    <p><?= $username ?></p>

</body>

</html>